name: bbmusic
description: '哔哔音乐，听歌自由'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+6

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  crypto: ^3.0.3
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  just_audio: ^0.9.39
  bot_toast: ^4.1.3
  uuid: ^4.3.3
  logger: ^2.2.0
  audio_service: ^0.18.13
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  dio: ^5.5.0+1
  cached_network_image: ^3.4.0
  path: ^1.9.0
  saver_gallery: ^3.0.5
  window_manager: ^0.4.2
  media_kit_libs_linux: ^1.1.3
  media_kit_libs_windows_audio: ^1.0.9
  just_audio_media_kit:
    git: https://github.com/lvyueyang/just_audio_media_kit
    # path: ../just_audio_media_kit
  media_kit_native_event_loop: ^1.0.8
  flutter_cache_manager: ^3.4.0
  package_info_plus: ^8.0.2
  file_picker: ^8.1.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: BBIcons
      fonts:
        - asset: assets/icons/icon.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
# https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  image_path: 'assets/ic_launch.png'
  android: true
  windows:
    generate: true
    image_path: 'assets/ic_launch.png'
  macos:
    generate: true
    image_path: 'assets/ic_launch.png'
